#!/bin/bash
export QB64_COMPILER=~/qb64-sdl/qb64/run_qb64.sh
export BSPWM_SOCKET=/tmp/bspwm-socket
unset TMUX

./scripts/dual_monitor.sh
xmodmap ~/.Xmodmap
#xcape -e 'Control_L=Caps_Lock;'

xset +fp /usr/share/fonts/local
xset fp rehash

xrdb ./.Xresources
if [ -z "$(pidof urxvtd)" ]; then
    urxvtd &
fi

rem -z -k'/home/dsman195276/scripts/remind_notify.sh %s &' &

unclutter -jitter 10 -reset -grab &
./scripts/redshift.sh &

PANEL_FIFO=/tmp/pan_fifo

case $1 in
  dev)
      exec /home/dsman195276/scripts/i3-wm-dev.sh
      killall conky
    ;;
  i3)
    export USE_COLORS=1
    exec /home/dsman195276/scripts/i3-wm.sh
    killall conky
    ;;
  subtle)
    exec subtle
    ;;
  spectrwm)
    xsetroot -cursor_name left_ptr
    nitrogen --restore
    pulseaudio &
    exec dbus-launch spectrwm
    ;;
  dwm)
    xsetroot -cursor_name left_ptr
    nitrogen --restore
    pulseaudio &
    exec dbus-launch dwm
    ;;
  bspwm)
    compton &
    xsetroot -cursor_name left_ptr
    nitrogen --restore
    sxhkd &
    [ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
    mkfifo "$PANEL_FIFO"
    exec bspwm -c /home/dsman195276/.config/bspwm/autostart -s "$PANEL_FIFO" -p W
    ;;
  xmonad)
    xsetroot -cursor_name left_ptr
    nitrogen --restore
    pulseaudio &
    exec dbus-launch xmonad
    ;;
  awesome)
    exec awesome
    ;;
	gnome)	
		exec dbus-launch gnome-session
		#exec dbus-launch gnome-session
		;;
	gnome-fallback)
		exec dbus-launch gnome-session --session=fallback
		;;
	kde)
		exec dbus-launch startkde
		;;
	mate)
		exec dbus-launch mate-session
		;;
	xfce4)
		exec startxfce4
		;;
	e17)
		exec dbus-launch enlightenment_start
		;;
	lightdm)
		exec sudo lightdm
		;;
	unity)
		exec gnome-session --session=ubuntu
		;;
	rox)
		exec rox
		;;
	cinnamon)
		exec cinnamon
		/usr/lib/gnome-settings-daemon/gnome-settings-daemon &
		;;
  fvwm)
    exec fvwm2
    ;;
  herb)
    exec herbstluftwm
    ;;
	*)
		export BROWSER=firefox
		export DE=openbox
		exec openbox-session
		;;
esac
TERM=screen

