URxvt*foreground: #e5e5e5 
URxvt*background: #1d1d1d
URxvt*cursorColor: #FFF9EC
!Black
URxvt*color0: #121212
URxvt*color8: #2e3436
!Red
URxvt*color1: #a35b66
URxvt*color9: #ab6b74
!Green
URxvt*color2: #99ab6f
URxvt*color10: #acb792
!Yellow
URxvt*color3: #ca9733
URxvt*color11: #ccaa69
!Blue
URxvt*color4: #495d6e
URxvt*color12: #687987
!Magenta
URxvt*color5: #825969
URxvt*color13: #977381
!Cyan
URxvt*color6: #839191
URxvt*color14: #98A4A4
!White
URxvt*color7: #E0E0E0
URxvt*color15: #e5e5e5
