URxvt*foreground:	#ebebeb
URxvt*background:	#101012

!black
URxvt*color0:	#1F1F1F
URxvt*color8:	#4d4d4d
!redc
URxvt*color1:	#A54242
URxvt*color9:	#CC6666 
!green
URxvt*color2:	#B7CE42
URxvt*color10:	#BDE077
!yellow
URxvt*color3:	#FEA63C
URxvt*color11:	#FFE863
!blue
URxvt*color4:	#66AABB
URxvt*color12:	#AACCBB
!magenta
URxvt*color5:	#B7416E
URxvt*color13:	#BB4466
!cyan
URxvt*color6:	#5E7175
URxvt*color14:	#A3BABF
!white
URxvt*color7:	#DDEEDD
URxvt*color15:	#6C887A
